### ISSUE TITLE
Install fails in exceptional circumstances

### ISSUE THREAD

**Issue by richardscarrott** [Kikobeats/is-url-http#15]
Install fails when:
1. Using yarn
2. Installing in docker
3. On Macbook Pro M1
4. When also depending on `@google-cloud/profiler`

<details>
  <summary>Click here to see the error output</summary>
  
  ```
$ docker build --tag is-url-http-docker-bug .
[+] Building 26.5s (8/9)
 => [internal] load build definition from Dockerfile                                                                                                                                                             0.0s
 => => transferring dockerfile: 353B                                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                                0.0s
 => => transferring context: 34B                                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/node:12.22.1                                                                                                                                                  1.1s
 => [internal] load build context                                                                                                                                                                                0.0s
 => => transferring context: 684B                                                                                                                                                                                0.0s
 => [1/5] FROM docker.io/library/node:12.22.1@sha256:a4b4ff31b471690ea908a64e919b482d71c3e05775e8a0318096bdd10cafeb32                                                                                            0.0s
 => CACHED [2/5] WORKDIR /usr/src/app                                                                                                                                                                            0.0s
 => CACHED [3/5] COPY package.json yarn.lock package-lock.json ./                                                                                                                                                0.0s
 => ERROR [4/5] RUN yarn install                                                                                                                                                                                25.3s
------
 > [4/5] RUN yarn install:
#8 0.246 yarn install v1.22.5
#8 0.279 [1/4] Resolving packages...
#8 0.326 [2/4] Fetching packages...
#8 3.485 [3/4] Linking dependencies...
#8 4.164 [4/4] Building fresh packages...
#8 4.696 error /usr/src/app/node_modules/pprof: Command failed.
#8 4.696 Exit code: 1
#8 4.696 Command: node-pre-gyp install --fallback-to-build
#8 4.696 Arguments:
#8 4.696 Directory: /usr/src/app/node_modules/pprof
#8 4.696 Output:
#8 4.696 node-pre-gyp info it worked if it ends with ok
#8 4.696 node-pre-gyp info using node-pre-gyp@1.0.8
#8 4.696 node-pre-gyp info using node@12.22.1 | linux | arm64
#8 4.696 node-pre-gyp info check checked for "/usr/src/app/node_modules/pprof/build/node-v72-linux-arm64-glibc/pprof.node" (not found)
#8 4.696 node-pre-gyp http GET https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v3.2.0/node-v72-linux-arm64-glibc.tar.gz
#8 4.696 node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v3.2.0/node-v72-linux-arm64-glibc.tar.gz
#8 4.696 node-pre-gyp WARN Pre-built binaries not installable for pprof@3.2.0 and node@12.22.1 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
#8 4.696 node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v3.2.0/node-v72-linux-arm64-glibc.tar.gz
#8 4.696 gyp info it worked if it ends with ok
#8 4.696 gyp info using node-gyp@8.4.1
#8 4.696 gyp info using node@12.22.1 | linux | arm64
#8 4.696 gyp info ok
#8 4.696 gyp info it worked if it ends with ok
#8 4.696 gyp info using node-gyp@8.4.1
#8 4.696 gyp info using node@12.22.1 | linux | arm64
#8 4.696 gyp ERR! find Python
#8 4.696 gyp ERR! find Python Python is not set from command line or npm configuration
#8 4.696 gyp ERR! find Python Python is not set from environment variable PYTHON
#8 4.696 gyp ERR! find Python checking if "python3" can be used
#8 4.696 gyp ERR! find Python - executable path is "/usr/bin/python3"
#8 4.696 gyp ERR! find Python - version is "3.5.3"
#8 4.696 gyp ERR! find Python - version is 3.5.3 - should be >=3.6.0
#8 4.696 gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
#8 4.696 gyp ERR! find Python checking if "python" can be used
#8 4.696 gyp ERR! find Python - executable path is "/usr/bin/python"
#8 4.696 gyp ERR! find Python - version is "2.7.13"
#8 4.696 gyp ERR! find Python - version is 2.7.13 - should be >=3.6.0
#8 4.696 gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
#8 4.696 gyp ERR! find Python
#8 4.696 gyp ERR! find Python **********************************************************
#8 4.696 gyp ERR! find Python You need to install the latest version of Python.
#8 4.696 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#8 4.696 gyp ERR! find Python you can try one of the following options:
#8 4.696 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#8 4.696 gyp ERR! find Python   (accepted by both node-gyp and npm)
#8 4.696 gyp ERR! find Python - Set the environment variable PYTHON
#8 4.696 gyp ERR! find Python - Set the npm configuration variable python:
#8 4.696 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#8 4.696 gyp ERR! find Python For more information consult the documentation at:
#8 4.696 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#8 4.696 gyp ERR! find Python **********************************************************
#8 4.696 gyp ERR! find Python
#8 4.696 gyp ERR! configure error
#8 4.696 gyp ERR! stack Error: Could not find any Python installation to use
#8 4.696 gyp ERR! stack     at PythonFinder.fail (/usr/src/app/node_modules/node-gyp/lib/find-python.js:330:47)
#8 4.696 gyp ERR! stack     at PythonFinder.runChecks (/usr/src/app/node_modules/node-gyp/lib/find-python.js:159:21)
#8 4.696 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/src/app/node_modules/node-gyp/lib/find-python.js:266:16)
#8 4.696 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/src/app/node_modules/node-gyp/lib/find-python.js:297:7)
#8 4.696 gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:7)
#8 4.696 gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
#8 4.696 gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
#8 4.696 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
#8 4.696 gyp ERR! System Linux 5.10.76-linuxkit
#8 4.696 gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/src/app/node_modules/pprof/build/node-v72-linux-arm64-glibc/pprof.node" "--module_name=pprof" "--module_path=/usr/src/app/node_modules/pprof/build/node-v72-linux-arm64-glibc" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
#8 4.696 gyp ERR! cwd /usr/src/app/node_modules/pprof
#8 4.696 gyp ERR! node -v v12.22.1
#8 4.696 gyp ERR! node-gyp -v v8.4.1
#8 4.696 gyp ERR! not ok
#8 4.696 node-pre-gyp ERR! build error
#8 4.696 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/pprof/build/node-v72-linux-arm64-glibc/pprof.node --module_name=pprof --module_path=/usr/src/app/node_modules/pprof/build/node-v72-linux-arm64-glibc --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
#8 4.696 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
#8 4.696 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
#8 4.696 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
#8 4.696 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
#8 4.696 node-pre-gyp ERR! System Linux 5.10.76-linuxkit
#8 4.696 node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/pprof/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#8 4.696 node-pre-gyp ERR! cwd /usr/src/app/node_modules/pprof
#8 4.696 node-pre-gyp ERR! node -v v12.22.1
#8 4.696 node-pre-gyp ERR! node-pre-gyp -v v1.0.8
#8 4.696 node-pre-gyp ERR! not ok
#8 4.696 Failed to execute '/usr/local/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/pprof/build/node-v72-linux-arm64-glibc/pprof.node --module_name=pprof --module_path=/usr/src/app/node_modules/pprof/build/node-v72-linux-arm64-glibc --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
#8 4.696 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install]: exit code: 1
error Command failed with exit code 1.
  ```
</details>

I know that's a very unique combination of variables which I doubt many other people will run into but I unfortunately have 🤬

For us, this package is a transitive dependency pulled in from using https://www.npmjs.com/package/@microlink/mql and, although I'm not 100% sure, I think it might be because this package depends on [`re2`](https://github.com/Kikobeats/is-url-http/blob/master/package.json#L36) which has some native bindings that could be the issue 🤷‍♂️. However, I don't think you actually need re2? Could it possibly be removed?

Example docker file
```
FROM node:12.22.1
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
CMD [ "node", "server.js" ]
```

Example package.json
```
{
  "name": "is-url-http-docker-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@google-cloud/profiler": "^4.1.7",
    "is-url-http": "^2.2.7"
  },
  "scripts": {
    "docker:build": "docker build --tag is-url-http-docker-bug ."
  }
}
```

**Comment by Kikobeats** [comment]
Hello, and sorry for this!

Your concern related to re2 is right. It's used by `url-regex-safe`:
[url-regex-safe](https://github.com/spamscanner/url-regex-safe/blob/master/src/index.js#L5)

As you can, see, the library has some logic to work even bindings are missing. 

The real problem here is the unexpected exit during the installation. You can try two things:

1) The error trace is saying python >=3.6.0 is not present in your system. What if you install it as part of your Dockerfile?
2) If after 1) it continues failing, try to perform [`yarn install --ignore-scripts`](https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-scripts) in your Dockerfile to prevent re2 installation.

**Comment by richardscarrott** [comment]
Hi @Kikobeats,

I've gone ahead and added `--ignore-scripts` which has solved the issue so thanks for the tip!

I guess all our other environments aren't running ARM CPUs (production servers and older MacBooks) so managed to download a prebuilt version of `pprof-nodejs`. I'm still none the wiser as to why it was only a problem in combination with `is-url-http`, but obv not an issue with this lib so I'll close the issue, thanks.
